---
title: "audio processing"
output: html_document
---

```{r}
read_rttm <- function(x,
                      from = NULL,
                      to = NULL) {
  if (length(readLines(x)) > 0) {
    res <- read.table(x, header = FALSE)
    colnames(res)[c(4, 5, 8)] <- c("start", "duration", "tier")
    res$end <- res$start + res$duration
  } else {
    res <- matrix(0, nrow = 0, ncol = 10)
    # res[1, ] <- NA
    colnames(res) <- paste0("V", 1:ncol(res))
    colnames(res)[c(4, 5, 8, 10)] <- c("start", "duration", "tier", "end")
    res <- data.frame(res)
  }

  if (!is.null(from)) {
    res <- res[res$end > from, ]
    if (nrow(res) > 0) {
      if (res$start[1] < from) {
        res$start[1] <- from
        res$duration[1] <- res$end[1] - res$start[1]
      }
    }
  }

  if (!is.null(to)) {
    res <- res[res$start < to, ]
    if (nrow(res) > 0) {
      if (res$end[nrow(res)] > to) {
        res$end[nrow(res)] <- to
        res$duration[nrow(res)] <- res$end[nrow(res)] - res$start[nrow(res)]
      }
    }
  }


  attributes(res)$filename <- basename(x)
  rownames(res) <- NULL
  res
}
```

```{r}
library(tidyverse)
library(ggthemes)
library(ggpubr)
```

# Read data

```{r setup, include=FALSE}

files <- list.files(path = "../Data/Rttm_Data",pattern = "all.rttm", recursive = TRUE)%>%
  str_subset(pattern = c("00000_00000020201016142243_0001A/all.rttm","191016_1319/all.rttm"), negate = T)

raw_data <- data_frame()
for (f in files) {
  jd <- read_rttm(paste("../Data/Rttm_Data/",f,sep=""))
  source <- str_sub(f,-14,-10)
  id <- str_sub(f,14,19)
  data <- jd %>% mutate(id = id, source = source)
  raw_data <- bind_rows(raw_data, data)
}

write_csv(raw_data, "../Data/merged_data/audio_video_comparison.csv")
```

# Visualize by tier and source

```{r}
ggplot(raw_data, aes(x = tier, ymin = start, ymax = end, col = source))+
  geom_linerange(position = position_dodge(width = 0.9), size = 4)+
  coord_flip()+
  #geom_segment(aes(x = start, y = tier, xend = end, yend = tier), size = 5, position = posi)+
  theme_minimal()+
  facet_grid(id~.)+
  #ylim(0,100)+
  scale_color_ptol()

ggsave("./plots/audio_video_comparison.png", width = 12, height = 16, scale = 1)
```

# Compare performance 
```{r}
comp_data <- raw_data %>%
  group_by(source, id)%>%
  summarise(length = max(end))%>%
  group_by(id)%>%
  summarise(length = min(length))%>%
  right_join(raw_data)%>%
  group_by(id)%>%
  filter(end < length)

```

## Correlation
```{r}
p_comp_data <- comp_data %>%
  group_by(id,source,tier)%>%
  summarise(count = n(),
            dur = sum(duration))%>%
  gather(type, value, -id, -source, -tier)%>%
  spread(source, value)

 
ggplot(p_comp_data, aes(x = Audio, y = Video))+
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = .5)+
  geom_point(alpha = .5)+
  facet_wrap(type ~ tier, scales = "free",nrow = 2)+
  stat_cor(method = "pearson",  aes(x = Audio, y = Video, label = paste(..rr.label..)), inherit.aes = F, size = 3)+
  theme_minimal()+
  theme(aspect.ratio = 1)
  

ggsave("./plots/audio_video_correlation.png", width = 12, height = 4, scale = 1)
```

## Absolute difference

```{r}
p_comp_data_abs <- comp_data %>%
  group_by(id,source,tier)%>%
  summarise(count = n(),
            duration = sum(duration))%>%
  gather(type, value, -id, -source, -tier)%>%
  spread(source, value)%>%
  mutate(diff = Audio - Video)

 
ggplot(p_comp_data_abs, aes(x = id, y = diff, col = tier))+
  geom_segment(aes(x = id, y = 0, xend = id, yend = diff), alpha = .5, col = "black")+
  geom_hline(yintercept = 0, lty = 2, alpha = .5)+
  geom_point(alpha = .5)+
  ylab("Audio - Video")+
  #geom_histogram(stat = "identity",alpha = .5)+
  facet_grid(tier ~type )+
  theme_minimal()+
  guides(x =  guide_axis(angle = 90))+
  scale_color_ptol()
  

ggsave("./plots/audio_video_diff.png", width = 5, height = 6, scale = 1)
```

# Hand checked data

## Export hand check data for CHI tier

```{r}
library(writexl)

raw_data %>%
  filter(tier == "CHI")%>%
  mutate(check = "")%>%
  select(id, source, tier, start,check)%>%
  group_by(source,id) %>%
  group_walk(~ write_csv(.x, paste0("../Data/merged_data/hand_check/",.y$id,"_",.y$source, ".xlsx")))

```

